### ISSUE TITLE
Balayage forme d'ours

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1222]
**Description**
Le balayage en ours est censé pouvoir être cast sans cible (ou avec cible alliée) ce n'est pas le cas actuellement

**Étapes de reproduction**
Mettz vous en forme d'ours, ne ciblez rien ou vous meme ou un allié, claquer l'enrager pour avoir de la rag essayer d'utiliser le balayage, ça ne fonctionne pas
- Druide
- Balayage

**Comportement attendu**
Le Balayage devrait se lancer et aoe autour du druide

**Captures d’écran / Vidéos**
Si possible et disponible, fournissez des captures d’écran ou vidéos du bug rencontre.

**Ressources additionnelles**
https://wowwiki-archive.fandom.com/wiki/Patch_3.1.0#Druids
Swipe: The Bear Form and Dire Bear Form version of this ability no longer has a targeting requirement and hits targets behind the druid and to the sides.

**Comment by Justforsoloq** [comment]
D'ailleurs vu qu'on est sur les balayages j'ai vu des gens parler du fait que le balayage de woe (feral/ours) prenait toujours pas en compte l'aoe-limit. 
Pas raid depuis longtemps donc pas pu vérifier. Mais si tu peux faire le package juste après

**Comment by Wilpok** [comment]
J'ai pas de log sur ça atm mais j'pourrais essayer d'voir, après j'me méfie tjrs des "wé j'pense que c'est bug etc..." mais pk pas jeter un coup d'oeil ça marche, si c'le cas j'referai un ticket dcp c'est un autre souci

**Comment by Justforsoloq** [comment]
https://wowwiki-archive.fandom.com/wiki/Area_damage_caps
Patch 3.3 will significantly alter the manner in which AoE damage cps are calculated. Instead of having a hard cap on the damage done, the maximum damage will be equal to the damage that would be dealt to 10 mobs hit by the ability. For example, if a spell does 1000 damage per target, it would deal 10000 total damage against 10 targets, and that would the maximum damage it could do against any number of targets (before critical effects are taken into account). Against 20 targets, the spell would do 500 damage per target, while against 40 targets the spell would do 250 damage per target. Against 10 or fewer targets, the spell would continue to do 1000 damage per target. Thus unlike pre-3.3 mechanics, the damage cap now scales with gear, the maximum number of targets that can receive full damage no longer scales inversely with gear, and the damage done once beyond target cap now also scales with gear.

**Comment by Justforsoloq** [comment]
Mais y genre à l'époque où je raidais encore (donc ya quelques mois) feral avaient pas de cap aoe (ce qui faisait que sur les phases des petits dragons ils avaient un dps stratosphérique), c'est pas très génant sauf peut être pour halions P3 si des braises s'accumulent

**Comment by Wilpok** [comment]
ouais j'ai vu et le FoK des rogue aussi j'pense (mais rien de confirmé) mais atm j'ai ni feral ni rogue pour tester xD

**Comment by Endalaust** [comment]
Ca t'intéresserais d'avoir les moyens de tester?

**Comment by Wilpok** [comment]
Bah si tu veux tester, tu pull 10mobs tu spam balayage en lion, et après tu en pull 50 ou 20 du meme genre (meme resistance, meme level etc...) et tu regardes si tu leur fais des dégats réduits ou pas

**Comment by Wilpok** [comment]
en soit c bcp plus simple sur ptr mais j'ai pas ça sous la main :')

**Comment by Endalaust** [comment]
Je sais pas tester, mais je peux te donner les moyens de le faire si tu le souhaite

**Comment by Wilpok** [comment]
Pourquoi pas, mais j'suis pas dispo ce soir

**Comment by Endalaust** [comment]
OK, viens échanger avec moi sur Discord à l'occasion, je suis sous le pseudo Amandil. On verra ensemble pour le moyen de t'aider à pousser tes tests. Je laisse les devs reprendre la suite du ticket

**Comment by joshwhedon** [comment]
Il n'y a pas de cible requise, et c'est cote client, vous pouvez lancer le sort sans selectionner une cible et une cible sera selectionnee automatiquement. Mais malgre tout, il faut qu'il y ait une cible a proximite qui puisse etre attaquee. C'est le comportement normal, et c'est gere par le client pas par le core.
L'autre bug sur les degats sur un grand nombre de cible sera corrige (en meme temps que le soucis sur la reduction de degats des betes de sang).
