### ISSUE TITLE
L'icd de l'enchantement couture est 15sec trop faible

### ISSUE THREAD

**Issue by Wilpok** [way-of-elendil/3.3.5#1228]
**Description**
L'ICD de l'enchantement de couture sur cape spell power (augmente de 295 la puissance des sorts est 15sec trop court

**Étapes de reproduction**
lancer un sort, faire proc son enchant, recommencer 30secondes après la fin du proc cela va reproc.

- Broderie Tisse lumière / LightWeave

**Comportement attendu**
(Je sais que dans la DB d'elendil c'est écrit le contraire, mais c'est erroné)

**Captures d’écran / Vidéos**
Ici le proc coutu sur elendil en raid (combat de boss) : 

![image](https://user-images.githubusercontent.com/65713751/111917670-9dee8180-8a81-11eb-8ce4-ba26ab3d0a15.png)
Les casters regagnent le proc 30sec après qu'il ait fade

Ici les logs de Method sous 3.3.5 : 

![image](https://user-images.githubusercontent.com/65713751/111917712-c1b1c780-8a81-11eb-8e60-5b27bdd98e66.png)

J'ai mis sur les boss encounters pour appuyer le fait que les joueurs tapent le boss en continu et donc augmentent les chances de proc dès que up.

**Comment by Wilpok** [comment]
https://www.mmo-champion.com/threads/677581-Best-professions-for-dps/page2

D'ailleurs je sais que c'pas une preuve mais l'apport considéré de la coutu en caster est de 73.75 arrondi a 73spell power soit 295 (le proc) /4

**Comment by Justforsoloq** [comment]
J'en profite pour étayer ton BT avec ça : 
https://www.wowhead.com/forums/topic/swordguard-embroidery-tailoring-vs-jc-144066
It was good when it had a 45 second internal cooldown, since it used to proc at the same time as most trinkets which inflated it's worth. With the embroideries ICD nerfed to 60 seconds, it has slipped below the other professions in terms of EP.

(J'imagine qu'il parle de 45s et de 60s en prenant en compte à partir du début du proc, ce qui revient à 30 et 45s à partir de la fin du proc, comme explique Wilpok)
