### ISSUE TITLE
[classe] Mage - Invisibilité permet la réutilisation des potions en combat

### ISSUE THREAD

**Issue by Ferro-woe** [way-of-elendil/3.3.5#1486]
**Description**
Il est possible de réutiliser des potions après avoir utilisé [Invisibilité](https://woehead.way-of-elendil.fr/?spell=66) lors d'un combat sur un boss, par exemple sur LK. On peut monter jusqu'à 4 réutilisations en 25hm, peut-être plus avec une bonne gestion.

**Étapes de reproduction**
1- Avec un mage (68 minimum), entrer en combat **sur un boss de raid** et utiliser une potion
2- Lancer [Invisibilité](https://woehead.way-of-elendil.fr/?spell=66)
3- Le temps de recharge de la potion est réinitialisé (pas normal)

**Comportement attendu**
Le temps de recharge de la potion ne devrait pas être réinitialisé par l'utilisation d'[Invisibilité](https://woehead.way-of-elendil.fr/?spell=66)

**Ressources additionnelles**
> Je précise à nouveau, il y a deux comportements différents en PvE sur les sorts d'invi.
> 
>  En Raid: tu ne peux pas drop le combat avec des invis à part si tout le reste du raid est mort (https://wowpedia.fandom.com/wiki/Combat)
> 
> 
> > Abilities that allow you to escape combat
> > Some classes have abilities that remove them from combat instantly. However, if they are [dotted](https://wowpedia.fandom.com/wiki/Damage_over_Time) they will usually be brought back into combat the next time they take damage. **Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly).**
> 
>  Le reste (aka donjons et "pve sauvage"): ton sort te fait bien sortir de combat

**Comment by Ferro-woe** [comment]
comportement tout à fait normal :
https://wowwiki-archive.fandom.com/wiki/Invisibility#Tips
*In PvP or PvE encounters you can use invisibility to remove yourself from combat allowing you to grab a quick food or drink and replenish your health and mana. Be mindful of the fact you're not DPSing while doing so, and only do this if it is critical and your Mana Gems, Evocation and Mana Potions are on cooldown. *

**Comment by sithis2a** [comment]
Tu peux réouvrir (cf Discord):
`Yo et non la mécanique d'invi est la même pour tout ces sorts (sinon un mage aurait le droit à 3-4 pots dans un raidboss fight comparé à 2 pour les autres classes, good class design).

https://us.forums.blizzard.com/en/wow/t/mage-invisibility/961380 => "You cant use it on raid bosses. I dont think vanish works either."

Dans ton lien => "In raids, while Invisibility can completely dump all your threat, it should be used if at all at the very beginning of the fight after offensive cooldowns ( [Icy Veins], damage trinkets, etc.) are first used to minimize high-DPS time lost." ils auraient dit pour reset la pot et switch de trinkets aussi sinon

De plus dans le 1er lien que j'avais link (https://github.com/WoWManiaUK/Redemption/issues/3587) => "Stealth level has nothing to do with being in combat or not. Players cannot exit combat on bosses on WOTLK, this is not even up to debate, read wiki or anything:
https://wow.gamepedia.com/Combat
"Some classes have abilities that remove them from combat instantly. However, if they are dotted they will usually be brought back into combat the next time they take damage. Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly). "
Hotfixes like this aren't listed in patch notes, I only recall it was done on BC because I was reading an article about it when fixing the ability.
Cause yeah, the combat wipes used to get you out of cb on mania, before we eventually fixed them not to. They can only exit you from combat if you are the last man standing in the fight and even that will often fail depending on the encounter."`

**Comment by sithis2a** [comment]
Je précise à nouveau, il y a deux comportements différents en PvE sur les sorts d'invi.
- En Raid: tu ne peux pas drop le combat avec des invis à part si tout le reste du raid est mort (https://wowpedia.fandom.com/wiki/Combat)
> Abilities that allow you to escape combat
Some classes have abilities that remove them from combat instantly. However, if they are [dotted](https://wowpedia.fandom.com/wiki/Damage_over_Time) they will usually be brought back into combat the next time they take damage. **Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly).**
- Le reste (aka donjons et "pve sauvage"): ton sort te fait bien sortir de combat

**Comment by Ferro-woe** [comment]
ça c'est une source valide

> Abilities that allow you to escape combat
> Some classes have abilities that remove them from combat instantly. However, if they are [dotted](https://wowpedia.fandom.com/wiki/Damage_over_Time) they will usually be brought back into combat the next time they take damage. **Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly).**

les autres concernent le voleur donc hors-sujet, puisqu'on parle du mage.

**Comment by Ferro-woe** [comment]
pour information l'utilisation de ce bug n'est pas sanctionné

> 07:08]Ferro: Bonjour.
Question pour le support. Est-il autorisé d'utiliser plusieurs potions lors d'un seul combat ? Je pense au mage sur LK qui peut réutiliser sa potion à chaque invisibilité, ça fait 3 à 4 par combat. 
[12:07]Vyr: Bonjour, oui.

**Comment by sithis2a** [comment]
> les autres concernent le voleur donc hors-sujet, puisqu'on parle du mage.
On discutait du vanish aussi à l'époque mais encore une fois dans le lien que je t'avais envoyé tu retrouves mon argument qui touche toutes les classes :)
<img width="816" alt="Capture d’écran 2023-03-11 à 12 49 51" src="https://user-images.githubusercontent.com/2728272/224483627-66927126-dff7-4cef-bc95-4f9f94577bc7.png">

**Comment by Ferro-woe** [comment]
Tu aurais dû linker ça directement.

La discussion te paraît tellement évidente que tu en déduis que les autres vont être convaincus rapidement, mais ça se passe pas comme ça. Tu imagines pas le nombre de faux arguments qui sont proposés, à force on se méfie des sources qu'on nous donne et on tri rapidement faute de mise en évidence claire.
Là, j'ai regardé, mais pas de façon aussi précise ; le fait que ça concerne le voleur, ça a mit un sacré coup dans la pertinence, et du coup, sur le cas général qui concerne aussi le mage, je suis passé complètement à coté de l'information.
C'est dommage par ce que l'information était là dès la première réponse sous discord, mais sans explication du contexte.

**Comment by Justforsoloq** [comment]
Les invisibilités sont traités de la même façon durant un combat de boss Ferro, donc qu'on parle du mage ou du rogue n'a pas d'importance.
Et sinon j'vois pas pourquoi vous discutez d'un truc qui est très simple depuis wotlk vanilla, t'as une pre-pot avant que le fight se lance, et une pot durant, et fin. Aucun vanish/invisi etc n'y change quelque chose.

**Comment by Ferro-woe** [comment]
par ce que sur LK on est à 4 ou 5

**Comment by Justforsoloq** [comment]
Oui et c'est un bug

**Comment by Ferro-woe** [comment]
le dire n'étant pas suffisant, il faut le démontrer avec des sources, d'où la discussion.
si tu continues à lire, tu verras que le 1er post a été modifié après la discussion justement ; tu as les détails si tu regardes les edited.
tu troll ou ...

**Comment by Justforsoloq** [comment]
C'est surtout ton deuxième poste qui porte à confusion, le "comportement tout à fait normal", suivi d'une quote qui ne porte pas sur un combat de boss raid c'est juste très décousu.

**Comment by MJ-Vyr** [comment]
Permet aussi d'éviter tout un tas de trucs qui devraient pas pouvoir être dodge.
