### ISSUE TITLE
Résistance: Canalisations PvE

### ISSUE THREAD

**Issue by Ischjgt** [way-of-elendil/3.3.5#278]
**Description**
Les canalisations prennent des résistances entières sur des NPCs, le sort est lancé mais la canalisation est coupée directement

**Comment by joshwhedon** [comment]
" *Resists: Due to most channeled spells being binary effects (with the exception of Arcane Missiles), such spells can only hit or miss; partial resists are not possible. This and the fact that those spells are cast instantly means that a resist will only cost the time of the Universal Cooldown instead of the whole channeling time. Therefore, especially long time channels are only minorly affected by resists."
https://worldofwarcraft.fandom.com/et/wiki/Channeling
https://wow.gamepedia.com/Channeling
Je crois pas que ce soit un bug
